server:
  port: 8081

spring:
#  profiles:
#    active: cloud
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/qacuser
#    url: jdbc:mysql://mysql-container:3306/qacuser
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: ${spring.application.name}
        heartbeat:
          enabled: true
jwt:
  secretKey: 9eJ8grwCm6h2bXY7bCZzvQU9GRjVQWI9fXbXSY8/j8U=
  validityInMilliseconds: 3600000
