server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    password: L8$gHn9%VzBx4Q!
    url: jdbc:mysql://qacmysql.cjuukq6e630o.ap-southeast-1.rds.amazonaws.com:3306/qacuser
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: ${spring.application.name}
        heartbeat:
          enabled: true