server:
  port: 8087

spring:
  main:
    allow-bean-definition-overriding: true
#  profiles:
#    active: cloud
  application:
    name: qna
  datasource:
    url: jdbc:mysql://localhost:3306/qna
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: ${spring.application.name}
        heartbeat:
          enabled: true

auth0:
  domain: dev-jr5iip1iu6v8pylo.us.auth0.com
  audience: https://dev-jr5iip1iu6v8pylo.us.auth0.com/api/v2/
  client-id: sXjfW7Ddyh5M7TitBBsm26Y9gsIStmdH
  client-secret: 49jsxl5AjYki5UX9coS_LAwIyYsPI7tbKmTy-vHYAZhnzvN18q5z2CL1qDjpzXU8
  management-api-url: https://dev-jr5iip1iu6v8pylo.us.auth0.com/api/v2