spring:
#  profiles:
#    active: cloud

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/
          audiences: https://qac.com
          jwk-set-uri: https://dev-jr5iip1iu6v8pylo.us.auth0.com/.well-known/jwks.json

  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
      host: localhost
      port: 8500

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://localhost:5173"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
              - "CONNECT"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
      routes:
        - id: comment
          uri: lb://event
          predicates:
            - Path=/comment/**
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By, QnAC Gateway Service
        - id: notification
          uri: lb://event
          predicates:
            - Path=/notification/**
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By, QnAC Gateway Service
        - id: qna
          uri: lb://qna
          predicates:
            - Path=/QnA/**
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By, QnAC Gateway Service
        - id: search
          uri: lb://search
          predicates:
            - Path=/search/**
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By, QnAC Gateway Service
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By, QnAC Gateway Service
        - id: vote
          uri: lb://vote
          predicates:
            - Path=/vote/**
          filters:
            - PrefixPath=/api/v1
            - AddResponseHeader=X-Powered-By, QnAC Gateway Service
        - id: websocket-route
          uri: lb://event
          predicates:
            - Path=/ws/**
          filters:
            - AddResponseHeader=X-Request-Type, WebSocket
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

server:
  ssl:
    key-store: classpath:certificate.pfx
    key-store-password: Admin123
    key-store-type: PKCS12
