server:
  port: 8085

spring:
#  profiles:
#    active: cloud
  application:
    name: vote
  data:
    mongodb:
      uri: mongodb://root:123456@mongodb-container:27017/vote?authSource=admin&retryWrites=true&w=majority
#      uri: mongodb://root:123456@localhost:27017/vote?authSource=admin&retryWrites=true&w=majority
  cloud:
    consul:
      host: consul-container
#      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: ${spring.application.name}
        heartbeat:
          enabled: true

management:
  health:
    mongo:
      enabled: false